/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package market;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author A455L
 */
public class dua extends javax.swing.JFrame {

    /**
     * Creates new form dua
     */
    public dua() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        qty = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        produk = new javax.swing.JTextField();
        kode = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        save = new javax.swing.JLabel();
        refresh = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edit = new javax.swing.JLabel();
        delete = new javax.swing.JLabel();
        clear = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        qty.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        qty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(qty);
        qty.setBounds(160, 230, 200, 40);

        harga.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        harga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(harga);
        harga.setBounds(160, 190, 200, 30);

        produk.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        produk.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(produk);
        produk.setBounds(160, 110, 200, 40);

        kode.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        kode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(kode);
        kode.setBounds(160, 70, 200, 30);

        des.setColumns(20);
        des.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        des.setRows(5);
        des.setBorder(null);
        jScrollPane1.setViewportView(des);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(160, 310, 200, 90);

        save.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveMouseClicked(evt);
            }
        });
        getContentPane().add(save);
        save.setBounds(494, 344, 100, 30);

        refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshMouseClicked(evt);
            }
        });
        getContentPane().add(refresh);
        refresh.setBounds(610, 350, 80, 70);

        jLabel2.setFont(new java.awt.Font("Segoe Marker", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("EDIT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(740, 350, 40, 20);

        edit.setFont(new java.awt.Font("Segoe Marker", 0, 18)); // NOI18N
        edit.setForeground(new java.awt.Color(255, 255, 255));
        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/market/3.PNG"))); // NOI18N
        edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editMouseClicked(evt);
            }
        });
        getContentPane().add(edit);
        edit.setBounds(720, 350, 90, 20);

        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        getContentPane().add(delete);
        delete.setBounds(710, 390, 90, 30);

        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMouseClicked(evt);
            }
        });
        getContentPane().add(clear);
        clear.setBounds(500, 390, 90, 30);

        tabel.setBackground(new java.awt.Color(153, 255, 153));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODE", "NAME", "PRICE", "QTY", "DESCRIPTIONS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);
        if (tabel.getColumnModel().getColumnCount() > 0) {
            tabel.getColumnModel().getColumn(0).setResizable(false);
            tabel.getColumnModel().getColumn(1).setResizable(false);
            tabel.getColumnModel().getColumn(2).setResizable(false);
            tabel.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(400, 100, 500, 220);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/market/W.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 540);

        setSize(new java.awt.Dimension(926, 581));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveMouseClicked
          if("".equals(kode.getText()) || "".equals(produk.getText()) || "".equals(harga.getText()) || "".equals(qty.getText()) || "".equals(des.getText())){
            JOptionPane.showMessageDialog(this, "Dilengkapi yaa!", "Error", JOptionPane.WARNING_MESSAGE);
        } else{
           
           String SQL = "INSERT INTO tb_product " + "VALUES('" + kode.getText()+ "','"+produk.getText()+"','"+harga.getText()+"','"+qty.getText()+"','"+des.getText()+"')";
           int status = KoneksiDB.execute(SQL);
           if(status == 1){
               JOptionPane.showMessageDialog(this, "Produk sudah ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
               selectData();
               
           }else{
               JOptionPane.showMessageDialog(this, "Produk gagal ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           }
        }
    }//GEN-LAST:event_saveMouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        int baris = tabel.getSelectedRow();
       if (baris != -1){
           String kode = tabel.getValueAt(baris, 0).toString();
           String SQL = "DELETE FROM tb_product WHERE Kode ='"+kode+"'";
           int status = KoneksiDB.execute(SQL);
           if(status == 1){
               JOptionPane.showMessageDialog(this, "Produk sudah dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
           } else{
               JOptionPane.showMessageDialog(this, "Produk gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
           }
       }else{
           JOptionPane.showMessageDialog(this, "Pilih baris dongg", "Error", JOptionPane.WARNING_MESSAGE);
       }
    }//GEN-LAST:event_deleteMouseClicked

    private void clearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMouseClicked
           kode.setText("");
           produk.setText("");
           harga.setText("");
           qty.setText("");
           des.setText("");

    }//GEN-LAST:event_clearMouseClicked

    private void refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshMouseClicked
                selectData();
    }//GEN-LAST:event_refreshMouseClicked

    private void editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editMouseClicked
         if("".equals(kode.getText()) || "".equals(produk.getText()) || "".equals(harga.getText()) || "".equals(qty.getText()) || "".equals(des.getText())){
                JOptionPane.showMessageDialog(this, "Hayo lengkapi sek", "Error", JOptionPane.WARNING_MESSAGE); 
              } else{
          
           String SQL = "UPDATE tb_product SET "
                   + "Nama='" + produk.getText()+"', "
                   + "Harga='"+harga.getText()+"', "
                   + "Qty='"+qty.getText()+"', "
                   + "Deskripsi='"+des.getText()+"' WHERE Kode='"+kode.getText()+"'";
           int status = KoneksiDB.execute(SQL);
           if(status == 1){
               JOptionPane.showMessageDialog(this, "Produk selesai di update", "Sukses", JOptionPane.INFORMATION_MESSAGE);
               selectData();
               
           }else{
               JOptionPane.showMessageDialog(this, "Produk gagal di update", "Sukses", JOptionPane.WARNING_MESSAGE);
           }
        }

    }//GEN-LAST:event_editMouseClicked

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
         int baris = tabel.getSelectedRow();
        
        if(baris != 1){
            kode.setText(tabel.getValueAt(baris, 0).toString());
            produk.setText(tabel.getValueAt(baris, 1).toString());
            harga.setText(tabel.getValueAt(baris, 2).toString());
            qty.setText(tabel.getValueAt(baris, 3).toString());
            des.setText(tabel.getValueAt(baris, 4).toString());
             }


    }//GEN-LAST:event_tabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dua.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dua().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clear;
    private javax.swing.JLabel delete;
    private javax.swing.JTextArea des;
    private javax.swing.JLabel edit;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kode;
    private javax.swing.JTextField produk;
    private javax.swing.JTextField qty;
    private javax.swing.JLabel refresh;
    private javax.swing.JLabel save;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

    public void selectData() {
       String kolom[] = {"Kode", "Nama", "Harga","Qty","Deskripsi"};
       DefaultTableModel dtm = new DefaultTableModel(null, kolom);
       String SQL = "SELECT * FROM tb_product";
       ResultSet rs = KoneksiDB.executeQuery(SQL);
       try{
           while(rs.next()){
               String Kode = rs.getString(1);
               String Nama = rs.getString(2);
               String Harga = rs.getString(3);
               String Qty = rs.getString(4);
               String Deskripsi = rs.getString(5);
               String data[] = {Kode,Nama,Harga, Qty, Deskripsi};
               dtm.addRow(data);
               
           }
           
       }catch (SQLException ex){
           Logger.getLogger(dua.class.getName()).log(Level.SEVERE, null, ex);
           
       }
       tabel.setModel(dtm);
    }
}
